# Generated by Django 4.0.5 on 2022-06-28 08:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, help_text='This will auto generate its value', max_length=155, null=True)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': "Patient's Profile",
                'db_table': 'tbl_patient_profile',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, help_text='This will auto generate its value', max_length=155, null=True)),
                ('appoinment_date', models.DateField(help_text='appoinment date')),
                ('appoinment_time', models.TimeField(help_text='appoinment time')),
                ('description', models.TextField(help_text='Description of appointment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_authentication.doctorprofile')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_authentication.receptionistprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'verbose_name': 'Appoinment Detail',
                'verbose_name_plural': 'Appoinment Details',
                'db_table': 'tbl_appoinment_details',
            },
        ),
    ]
